#tray icon and notifications
string_running="Usługa powiadomień Bajton Helper"
string_show_window="Pokaż okno"
string_exit="Zamknij aplikację"
string_source="Kod źródłowy"
string_autofill_success=" zadania są rozwiązane!"
string_autofill_desc="Automatycznie przesłano Twoją poprzednią odpowiedź."
string_contest_alert="⚠ Przypomnienie o terminie"
string_contest_deadline=" kończy się w ciągu "
string_new_problem="📄 Nowe zadanie"
#contests tab
string_contests="Hasła"
string_contests_desc="Jeśli chcesz, aby aplikacja działała dla konkursów chronionych hasłami, wprowadź je do tej tabelki.\nKliknij dwukrotnie komórkę, aby edytować."
string_name="Tytuł"
string_password="Hasło"
string_not_required="Brak hasła"
string_import="📥 Importuj"
string_export="📤 Eksportuj"
string_contests_passwords=" hasła do konkursów"
string_txt_ad="#######\nBajton Helper by Piotr Trybisz\nSprawdź: https://github.com/PetrusTryb/bajton-helper"
#search tab
string_search="Wyszukiwarka"
string_search_desc="Tutaj możesz wyszukiwać zadania (publiczne oraz z konkursów, do których masz dostęp)"
string_searching="Wyszukiwanie, proszę czekać..."
string_problem_name="Nazwa zadania"
string_contest_name="Konkurs"
string_actions="Akcje"
string_no_actions="Brak dostępnych akcji"
string_auto_solve="Wyszukaj rozwiązanie"
string_contest_invalid="Konkurs wygasł lub jeszcze się nie rozpoczął."
string_solving="Wyszukiwanie Twoich poprzednich dobrych rozwiązań, proszę czekać..."
string_solve_error="Nie udało się wysłać rozwiązania"
string_solve_failed="Nie odnaleziono poprzednich dobrych rozwiązań. Sprawdź, czy wprowadziłeś hasła do wszystkich konkursów w karcie Hasła."
string_note="To nie jest narzędzie hakerskie. Po prostu kopiuje Twoje poprzednie rozwiązania do tego samego zadania."
string_unsolved="Nierozwiązane"
string_partial="Częściowo poprawne"
string_wrong="Niepoprawne"
#notifications tab
string_notifications="Powiadomienia"
string_notifications_desc="Tutaj możesz dostosować opcje powiadomień.\nUwaga: ta funkcja działa tylko, gdy aplikacja jest uruchomiona. Autostart aplikacji możesz włączyć w ustawieniach."
string_public_problems="Zadania publiczne"
string_new_problems_notify="Powiadamiaj o nowych zadaniach"
string_new_problems_autofill="Prześlij automatycznie, jeśli już rozwiązane"
string_contests_problems="Konkursy"
string_ending_contests_notify="Powiadom mnie, kiedy konkurs kończy się w ciągu:"
string_interval="Częstotliwość sprawdzania"
string_check_now="Sprawdź teraz"
#settings tab
string_settings="Ustawienia"
string_my_data="Moje dane"
string_props_warning="Nie udostępniaj pliku props.ini! Zawiera dane dostępowe do Twojego konta."
string_clear_data="Wyczyść wszystkie dane przy wylogowywaniu (usunie hasła do konkursów i ustawienia)"
string_theme="Motyw"
string_dark="Ciemny"
string_light="Jasny"
string_start_options="Opcje uruchamiania"
string_autorun="Uruchamiaj wraz z systemem"
string_minimize="Zminimalizuj do paska powiadomień przy uruchamianiu"
string_legal="Aplikacja powstała w celach edukacyjnych. Nie służy do atakowania aplikacji Online Judge."
#login and logout
string_connect_error="Nie można połączyć się z serwerem."
string_logout="Wyloguj i zamknij"
string_logout_question="Czy chcesz się wylogować i zamknąć aplikację?"
string_data_warning="UWAGA: Wszystkie dane aplikacji zostaną usunięte!"
string_unauthorized="Nie jesteś już zalogowany. Zrestartuj aplikację Bajton Helper i zaloguj się ponownie."
string_hard_error="Aplikacja Bajton Helper przestała działać z powodu błędu:"
string_login_desc="Zaloguj się na konto Bajton. Aplikacja zachowa jedynie identyfikator sesji (nie zachowa hasła)."
string_login_error="Błąd logowania"