#tray icon and notifications
string_running="Bajton Helper notifications service"
string_show_window="Show window"
string_exit="Full exit"
string_source="Source code"
string_autofill_success=" problems auto-filled!"
string_autofill_desc="We have copied Your previous answers so You don't have to solve these problems again."
string_contest_alert="⚠ Contest deadline alert"
string_contest_deadline=" is ending in less than "
string_new_problem="📄 New problem"
#contests tab
string_contests="Passwords"
string_contests_desc="If You want to use this app in password-protected contests, please enter passwords to this table.\nDouble-click on a password cell to edit."
string_name="Title"
string_password="Password"
string_not_required="Not required"
string_import="📥 Import"
string_export="📤 Export"
string_contests_passwords=" contests passwords"
string_txt_ad="#######\nBajton Helper by Piotr Trybisz\nDownload: https://github.com/PetrusTryb/bajton-helper"
#search tab
string_search="Search"
string_search_desc="Here You can search for particular problem by it's name in public problems and all contests that You have access to."
string_searching="Searching, please wait..."
string_problem_name="Problem name"
string_contest_name="Contest"
string_actions="Actions"
string_no_actions="No actions avaiable"
string_auto_solve="Auto-solve"
string_contest_invalid="Sorry, this contest has ended or not yet started."
string_solving="We are looking up for Your previous answers, please wait..."
string_solve_error="Auto-solve failed"
string_solve_failed="Failed to find correct answer. Ensure You have provided passwords for all constests that You took part in."
string_note="This isn't a cheat. It only copies Your previous answers from Your account."
string_unsolved="Unsolved"
string_partial="Partial"
string_wrong="Wrong"
#notifications tab
string_notifications="Notifications"
string_notifications_desc="Here You can manage notifications service.\nPlease note that this function is experimental.\nIt will work only when the app is running - please check autostart options in Settings."
string_public_problems="Public problems"
string_new_problems_notify="Notify about new problems"
string_new_problems_autofill="Fill automatically if previously solved"
string_contests_problems="Contests"
string_ending_contests_notify="Notify about ending contests when deadline is closer than:"
string_interval="Check interval"
string_check_now="Check now"
#settings tab
string_settings="Settings"
string_my_data="My data"
string_props_warning="Do not share the props.ini file! It contains informations that may be used to steal Your account."
string_clear_data="Clear all data at logout (this will clear all settings and contests passwords)"
string_theme="Interface theme"
string_dark="Dark"
string_light="Light"
string_start_options="Start options"
string_autorun="Run at system startup"
string_minimize="Start minimized to tray"
string_legal="This app is made for educational purposes. It is not for cheating or hacking Online Judge app."
#login and logout
string_connect_error="Cannot connect to Online Judge. Server may be down."
string_logout="Sign out and close"
string_logout_question="Are You sure that You want to log out and exit the app?"
string_data_warning="WARNING: Bajton Helper app data WILL BE PERMANENTLY REMOVED!"
string_unauthorized="You are not logged in. Please restart the app and sign in."
string_hard_error="Bajton helper has stopped because of hard error:"
string_login_desc="Please log-in using Bajton account. App will store only session id (not password)."
string_login_error="Auth error"